### ISSUE TITLE
如果我装油猴2.3.1再升级到最新版，该脚本就没法加载大图了

### ISSUE THREAD

**Issue by nomosaic** [gameclamp/ChaoJiexhentai#1]
因为某些原因我退回到油猴2.3.1那个有签名的版本 我再更新到最新版油猴的时候 我发现这个脚本就不能加载大图了 意思就是看图器只显示缩略图 点每个缩略图就还是像没用过脚本那样直接链接到单图页面了

**Comment by gameclamp** [comment]
要使用3.2以上的版本，另外按QA.1做一下https://github.com/gameclamp/ChaoJiexhentai#qa

**Comment by nomosaic** [comment]
我做了 没什么用啊 怎样才看得出效果呢？ 还有旁边的open和get是什么意思？

**Comment by gameclamp** [comment]
清理一下缓存呢？
如果还不行，你需要按ctrl+shift+k打开控制台，看看脚本运行的时候有什么错误。
open和get只是测试用，没什么实际意义。

**Comment by nomosaic** [comment]
更新到火狐41总算是正常了 怪事
